=== balajidr/Web-Technology-Lab/cars.dtd
<?xml version = "1.0"  encoding = "utf-8"?>
  <!ELEMENT car_catalog (car+)>
  <!ELEMENT car (year, make, model, color, engine, number_of_doors, transmission_type, accessories)>
  <!ELEMENT make (#PCDATA)>
  <!ELEMENT model (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT color (#PCDATA)>
  <!ELEMENT engine (number_of_cylinders, fuel_system)>
  <!ELEMENT number_of_doors (#PCDATA)>
  <!ELEMENT transmission_type (#PCDATA)>
  <!ELEMENT accessories (#PCDATA)>
  <!ELEMENT number_of_cylinders (#PCDATA)>
  <!ELEMENT fuel_system (#PCDATA)>

  <!ATTLIST accessories radio CDATA #REQUIRED>
  <!ATTLIST accessories air_conditioning CDATA #REQUIRED>
  <!ATTLIST accessories power_windows CDATA #REQUIRED>
  <!ATTLIST accessories power_steering CDATA #REQUIRED>
  <!ATTLIST accessories power_brakes CDATA #REQUIRED>

  <!ENTITY m "Mini">
  <!ENTITY b "Mercedes-Benz">
  <!ENTITY a "Audi">
  <!ENTITY l "Lamborghini">
  <!ENTITY f "Ferrari">
  <!ENTITY t "Toyota">

=== balajidr/Web-Technology-Lab/cars.xml
<?xml version = "1.0"  encoding = "utf-8"?>
<!DOCTYPE car_catalog SYSTEM "cars.dtd">
<?xml-stylesheet type = "text/css" href = "cars.css"?>
<?xml-stylesheet type = "text/xsl" href = "cars.xsl"?>
  <car_catalog>
    <car>
      <make> bmw </make>
      <model>  i8 </model>
      <color> Black </color>
      <year> 2017 </year>
      <engine>Engine Specifications
        <number_of_cylinders> 8 cylinder
        </number_of_cylinders>
        <fuel_system> Multi-Port Fuel Injected </fuel_system>
      </engine>
      <number_of_doors> 2 door </number_of_doors>
      <transmission_type> 6 speed automatic
      </transmission_type>
      <accessories radio = "yes"  air_conditioning = "yes"
                    power_windows = "yes"
                    power_steering = "yes"
                    power_brakes = "yes" />
    </car>
    <car>
      <make> tesla </make>
      <model>model 3 </model>
      <color> Brown </color>
      <year> 2005 </year>
      <engine>Engine Specifications
        <number_of_cylinders> 8 cylinder
        </number_of_cylinders>
        <fuel_system> 4BBL Kompressor </fuel_system>
      </engine>
      <number_of_doors> 4 door </number_of_doors>
      <transmission_type> 4 speed automatic </transmission_type>
      <accessories radio = "yes"  air_conditioning = "yes"
                    power_windows = "yes"  power_steering = "yes"
                    power_brakes = "no" />
    </car>
    <car>
      <make> faraday </make>
      <model> future </model>
      <color> White </color>
      <year> 2015 </year>
      <engine>Engine Specifications
        <number_of_cylinders> 4 cylinder
        </number_of_cylinders>
        <fuel_system> electric </fuel_system>
      </engine>
      <number_of_doors> 2 door </number_of_doors>
      <transmission_type> 4 speed manual </transmission_type>
      <accessories radio = "no"  air_conditioning = "yes"
                    power_windows = "yes"  power_steering = "yes"
                    power_brakes = "yes" />
    </car>
  </car_catalog>
